version: "3.1"

services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=yourpassword
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - WEBHOOK_TUNNEL_URL=https://<YOUR-RENDER-URL>
      - VUE_APP_URL_BASE_API=https://<YOUR-RENDER-URL>/
      - NODE_ENV=production
