services:
  - type: web
    name: n8n
    env: docker
    plan: free
    repo: https://github.com/sebby1216/n8n-render-demo
    branch: main
    dockerfilePath: docker/images/n8n/Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "pass123"
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_PORT
        value: "5678"
      - key: WEBHOOK_TUNNEL_URL
        value: "https://telebotexp.onrender.com/"
      - key: VUE_APP_URL_BASE_API
        value: "https://telebotexp.onrender.com/"
      - key: NODE_ENV
        value: "production"
